
-- /***
-- *** Requester Name:  Naveen Kumar Gupta
-- *** Purpose : create tables SK_CONFIGURATOR_DESCRIPTION,SK_IPCKMAT_DESCRIPTION and add cols into tables SK_CONFIGURATOR and SK_IPCKMAT;
-- *** Schema  : atgpub
-- *** Date of Request : 25/04/2017


-- Create table SK_CONFIGURATOR_DESCRIPTION
 CREATE TABLE SK_CONFIGURATOR_DESCRIPTION 
   (	ASSET_VERSION INT NOT NULL, 
	LANGUAGE VARCHAR2(2), 
	DESCRIPTION CLOB, 
	CONFIG_ID VARCHAR2(6),
	CONSTRAINT SK_CONFIG_DESC_PK PRIMARY KEY (ASSET_VERSION,LANGUAGE,CONFIG_ID)
   );

-- Create table SK_IPCKMAT_DESCRIPTION
CREATE TABLE SK_IPCKMAT_DESCRIPTION 
   (	ASSET_VERSION INT NOT NULL, 
	LANGUAGE VARCHAR2(2), 
	DESCRIPTION CLOB, 
	IPC_KMAT_ID VARCHAR2(40),
	CONSTRAINT SK_IPCKMAT_DESC_PK PRIMARY KEY (ASSET_VERSION,LANGUAGE,IPC_KMAT_ID)
   );

   
   -- alter table SK_CONFIGURATOR
ALTER TABLE SK_CONFIGURATOR ADD DEFAULT_DESC CLOB;

-- alter table SK_IPCKMAT
ALTER TABLE SK_IPCKMAT ADD (DEFAULT_DESC CLOB, KB_VALIDATION_ENABLED NUMBER(1,0), RESTRICTED_FOR_INTRANET NUMBER(1,0));