alter table sk_prd_ctlg_dtls add(np_country_of_origin varchar2(3),
				np_storage_location varchar2(4),
				np_supplier varchar2(10),
				np_supplier_country varchar2(3),
				np_special_supplier varchar2(10),
				np_delivery_time_on_request numeric(1),
				np_delivery_time varchar2(3),
				np_minimum_quantity numeric(17),
				np_packaging_type varchar2(3),
				np_packaging_unit varchar2(3),	
				np_customs_number varchar2(3),
				np_eccn varchar2(14),
				np_eccn_release varchar2(1),
				np_eccn_release_date varchar2(8),
				np_export_list_number varchar2(14),
				np_preference_on_request numeric(1),
				np_pref_country_of_origin varchar2(3),
				np_definite_country_of_origin varchar2(3),
				np_packaging_quantity varchar2(13),
				np_packaging_quantity_large numeric(17,3),
				rp_country_of_origin varchar2(3),
				rp_storage_location varchar2(4),
				rp_supplier varchar2(10),
				rp_supplier_country varchar2(3),
				rp_special_supplier varchar2(10),
				rp_delivery_time_on_request numeric(1),
				rp_delivery_time varchar2(3),
				rp_minimum_quantity numeric(17),
				rp_packaging_type varchar2(3),
				rp_packaging_unit varchar2(3),
				rp_customs_number varchar2(3),
				rp_eccn varchar2(14),
				rp_eccn_release varchar2(1),
				rp_eccn_release_date varchar2(8),
				rp_export_list_number varchar2(14),
				rp_preference_on_request numeric(1),
				rp_pref_country_of_origin varchar2(3),
				rp_definite_country_of_origin varchar2(3),
				rp_packaging_quantity varchar2(13),
				rp_packaging_quantity_large numeric(17,3),
				bb_country_of_origin varchar2(3),
				bb_storage_location varchar2(4),
				bb_supplier varchar2(10),
				bb_supplier_country varchar2(3),
				bb_special_supplier varchar2(10),
				bb_delivery_time_on_request numeric(1),
				bb_delivery_time varchar2(3),
				bb_minimum_quantity numeric(17),
				bb_packaging_type varchar2(3),
				bb_packaging_unit varchar2(3),
				bb_customs_number varchar2(3),
				bb_eccn varchar2(14),
				bb_eccn_release varchar2(1),
				bb_eccn_release_date varchar2(8),
				bb_export_list_number varchar2(14),
				bb_preference_on_request numeric(1),
				bb_pref_country_of_origin varchar2(3),
				bb_definite_country_of_origin varchar2(3),
				bb_packaging_quantity varchar2(13),
				bb_packaging_quantity_large numeric(17,3),
				sp_country_of_origin varchar2(3),
				sp_storage_location varchar2(4),
				sp_supplier varchar2(10),
				sp_supplier_country varchar2(3),
				sp_special_supplier varchar2(10),
				sp_delivery_time_on_request numeric(1),
				sp_delivery_time varchar2(3),
				sp_minimum_quantity numeric(17),
				sp_packaging_type varchar2(3),
				sp_packaging_unit varchar2(3),
				sp_customs_number varchar2(3),
				sp_eccn varchar2(14),
				sp_eccn_release varchar2(1),
				sp_eccn_release_date varchar2(8),
				sp_export_list_number varchar2(14),
				sp_preference_on_request numeric(1),
				sp_pref_country_of_origin varchar2(3),
				sp_definite_country_of_origin varchar2(3),
				sp_packaging_quantity varchar2(13),
				sp_packaging_quantity_large numeric(17,3)
				);
				
drop table sk_preferential_zone;	
create table sk_np_preferential_zone(
		preferential_zone_key 			varchar(4),
		preferential_zone 			varchar(4),
		id 		varchar2(40),
  constraints 	sk_np_preferential_zone_pk primary key (id,preferential_zone_key));
  
  create table sk_rp_preferential_zone(
		preferential_zone_key 			varchar(4),
		preferential_zone 			varchar(4),
		id 		varchar2(40),
  constraints 	sk_rp_preferential_zone_pk primary key (id,preferential_zone_key));
  
  create table sk_sp_preferential_zone(
		preferential_zone_key 			varchar(4),
		preferential_zone 			varchar(4),
		id 		varchar2(40),
  constraints 	sk_sp_preferential_zone_pk primary key (id,preferential_zone_key));
  
  create table sk_bb_preferential_zone(
		preferential_zone_key 			varchar(4),
		preferential_zone 			varchar(4),
		id 		varchar2(40),
  constraints 	sk_bb_preferential_zone_pk primary key (id,preferential_zone_key));