UPDATE SK_DEFAULTUILANG SET DEFAULTUILANG='en' WHERE DEFAULTUILANG_ID='en';
UPDATE SK_DEFAULTUILANG SET DEFAULTUILANG='de' WHERE DEFAULTUILANG_ID='de';

INSERT INTO SK_DEFAULTUILANG VALUES('es','es');

COMMIT;