/***
*** Requester Name:  	Swaminath Chengannagari
*** Purpose :		 	SK-41034
*** Schema  :		 	atgcore
*** Date of Request : 	May 10, 2017
***/

DELETE FROM SK_ORG_SETTINGS WHERE ORG_SETTING_ID='601_Disp_Pay_Trms' AND ID='600001';
DELETE FROM SK_ORG_SETTINGS WHERE ORG_SETTING_ID='202_Disp_Pay_Trms' AND ID='200002';
DELETE FROM SK_ORG_SETTINGS WHERE ORG_SETTING_ID='403_Disp_Pay_Trms' AND ID='400003';
DELETE FROM SK_ORG_SETTINGS WHERE ORG_SETTING_ID='303_Disp_Pay_Trms' AND ID='300003';
DELETE FROM SK_ORG_SETTINGS WHERE ORG_SETTING_ID='404_Disp_Pay_Trms' AND ID='400004';
DELETE FROM SK_ORG_SETTINGS WHERE ORG_SETTING_ID='101_Disp_Pay_Trms' AND ID='100001';
DELETE FROM SK_ORG_SETTINGS WHERE ORG_SETTING_ID='401_Disp_Pay_Trms' AND ID='400001';
DELETE FROM SK_ORG_SETTINGS WHERE ORG_SETTING_ID='402_Disp_Pay_Trms' AND ID='400002';
DELETE FROM SK_ORG_SETTINGS WHERE ORG_SETTING_ID='102_Disp_Pay_Trms' AND ID='100002';
DELETE FROM SK_ORG_SETTINGS WHERE ORG_SETTING_ID='103_Disp_Pay_Trms' AND ID='100003';
DELETE FROM SK_ORG_SETTINGS WHERE ORG_SETTING_ID='104_Disp_Pay_Trms' AND ID='100004';
DELETE FROM SK_ORG_SETTINGS WHERE ORG_SETTING_ID='301_Disp_Pay_Trms' AND ID='300001';
DELETE FROM SK_ORG_SETTINGS WHERE ORG_SETTING_ID='302_Disp_Pay_Trms' AND ID='300002';
DELETE FROM SK_ORG_SETTINGS WHERE ORG_SETTING_ID='203_Disp_Pay_Trms' AND ID='200003';
DELETE FROM SK_ORG_SETTINGS WHERE ORG_SETTING_ID='201_Disp_Pay_Trms' AND ID='200001';
DELETE FROM SK_ORG_SETTINGS WHERE ORG_SETTING_ID='t02_Disp_Pay_Trms' AND ID='T02239';

DELETE FROM SK_ORG_PROPERTY WHERE ID='601_Disp_Pay_Trms';
DELETE FROM SK_ORG_PROPERTY WHERE ID='202_Disp_Pay_Trms';
DELETE FROM SK_ORG_PROPERTY WHERE ID='403_Disp_Pay_Trms';
DELETE FROM SK_ORG_PROPERTY WHERE ID='303_Disp_Pay_Trms';
DELETE FROM SK_ORG_PROPERTY WHERE ID='404_Disp_Pay_Trms';
DELETE FROM SK_ORG_PROPERTY WHERE ID='101_Disp_Pay_Trms';
DELETE FROM SK_ORG_PROPERTY WHERE ID='402_Disp_Pay_Trms';
DELETE FROM SK_ORG_PROPERTY WHERE ID='401_Disp_Pay_Trms';
DELETE FROM SK_ORG_PROPERTY WHERE ID='102_Disp_Pay_Trms';
DELETE FROM SK_ORG_PROPERTY WHERE ID='103_Disp_Pay_Trms';
DELETE FROM SK_ORG_PROPERTY WHERE ID='104_Disp_Pay_Trms';
DELETE FROM SK_ORG_PROPERTY WHERE ID='301_Disp_Pay_Trms';
DELETE FROM SK_ORG_PROPERTY WHERE ID='302_Disp_Pay_Trms';
DELETE FROM SK_ORG_PROPERTY WHERE ID='203_Disp_Pay_Trms';
DELETE FROM SK_ORG_PROPERTY WHERE ID='201_Disp_Pay_Trms';
DELETE FROM SK_ORG_PROPERTY WHERE ID='t02_Disp_Pay_Trms';

DELETE FROM SK_PROPERTY WHERE PROPERTY_ID = 'Display_Payment_Terms_Order_Mamt' AND GROUP_ID = 'Cart_Display';

COMMIT;