/***
*** Requester Name:  Alok Bansal
*** Purpose : SQL for droping Columns in SK_ITEM_PRICE and SK_ORDER_PRICEINFO
*** Schema  : Core/Staging
*** Date of Request : 19/05/2017
***/

ALTER TABLE SK_ITEM_PRICE DROP QUOTE_GALP_VALUE;

ALTER TABLE SK_ITEM_PRICE DROP QUOTE_GALP_CURRENCY;

ALTER TABLE SK_ITEM_PRICE DROP QCP_VALUE;

ALTER TABLE SK_ITEM_PRICE DROP QCP_CURRENCY;

ALTER TABLE SK_ITEM_PRICE DROP QUOTE_MARGIN;




ALTER TABLE SK_ORDER_PRICEINFO DROP GALPT_VALUE;

ALTER TABLE SK_ORDER_PRICEINFO DROP GALPT_CURRENCY;

ALTER TABLE SK_ORDER_PRICEINFO DROP GAQPT_VALUE;

ALTER TABLE SK_ORDER_PRICEINFO DROP GAQPT_CURRENCY;

ALTER TABLE SK_ORDER_PRICEINFO DROP QUOTE_MARGIN_TOTAL;

