/***
*** Requester Name	:	Prasanna K Sinha
*** Purpose 		:	SK-63444
*** Schema  		:	Core
*** Date of Request :	22/09/2017
***/

DELETE FROM SK_ACTIVITY WHERE NAME='OUD_UPDATE_BUS_ROLE_ACTIVITY';

DELETE FROM SK_ACTIVITY WHERE NAME='ATG_UPDATE_BUS_ROLE_ACTIVITY';

DELETE FROM SK_WORKFLOW WHERE  NAME='UPDATE_BUSINESS_ROLE';

COMMIT;