/***
*** Requester Name:  	Swaminath Chengannagari
*** Purpose :		 	SK-50195
*** Schema  :		 	atgcore
*** Date of Request : 	April 27, 2017
***/

DELETE FROM SK_PROPERTY_REL_ORG WHERE PROPERTY_ID = 'Certified_Partner' AND ORGANIZATION_TYPE = 'company';
DELETE FROM SK_PROPERTY_REL_ORG WHERE PROPERTY_ID = 'Is_MC_Company' AND ORGANIZATION_TYPE = 'company';
DELETE FROM SK_PROPERTY_REL_ORG WHERE PROPERTY_ID = 'List_Price_Type' AND ORGANIZATION_TYPE = 'company';
DELETE FROM SK_PROPERTY_REL_ORG WHERE PROPERTY_ID = 'Show_Discount' AND ORGANIZATION_TYPE = 'company';
DELETE FROM SK_PROPERTY_REL_ORG WHERE PROPERTY_ID = 'Show_Customer_Price' AND ORGANIZATION_TYPE = 'company';
DELETE FROM SK_PROPERTY_REL_ORG WHERE PROPERTY_ID = 'Create_Quote' AND ORGANIZATION_TYPE = 'company';
DELETE FROM SK_PROPERTY_REL_ORG WHERE PROPERTY_ID = 'Allow_Editing_Of_Price' AND ORGANIZATION_TYPE = 'company';
DELETE FROM SK_PROPERTY_REL_ORG WHERE PROPERTY_ID = 'Allow_Editing_Of_Quote' AND ORGANIZATION_TYPE = 'company';
DELETE FROM SK_PROPERTY_REL_ORG WHERE PROPERTY_ID = 'oci_cxml_profile' AND ORGANIZATION_TYPE = 'company';
DELETE FROM SK_PROPERTY_REL_ORG WHERE PROPERTY_ID = 'ERP2Mall_Stop_Options' AND ORGANIZATION_TYPE = 'company';
DELETE FROM SK_PROPERTY_REL_ORG WHERE PROPERTY_ID = 'SO_Article_Not_Found' AND ORGANIZATION_TYPE = 'company';
DELETE FROM SK_PROPERTY_REL_ORG WHERE PROPERTY_ID = 'E2M_Order_Contains_SN_Product' AND ORGANIZATION_TYPE = 'company';
DELETE FROM SK_PROPERTY_REL_ORG WHERE PROPERTY_ID = 'Stop_In_Case_of_Software_Product' AND ORGANIZATION_TYPE = 'company';
DELETE FROM SK_PROPERTY_REL_ORG WHERE PROPERTY_ID = 'SO_Different_Price' AND ORGANIZATION_TYPE = 'company';
DELETE FROM SK_PROPERTY_REL_ORG WHERE PROPERTY_ID = 'SO_Request_Delivery_Date_Not_Possible' AND ORGANIZATION_TYPE = 'company';
DELETE FROM SK_PROPERTY_REL_ORG WHERE PROPERTY_ID = 'SO_Invalid_SPA_Number' AND ORGANIZATION_TYPE = 'company';
DELETE FROM SK_PROPERTY_REL_ORG WHERE PROPERTY_ID = 'SO_Available_Successor_Part_Number' AND ORGANIZATION_TYPE = 'company';
DELETE FROM SK_PROPERTY_REL_ORG WHERE PROPERTY_ID = 'SO_Min_Order_Quantity_Not_Achieved' AND ORGANIZATION_TYPE = 'company';
DELETE FROM SK_PROPERTY_REL_ORG WHERE PROPERTY_ID = 'SO_Min_Order_Value_Not_Exceeded' AND ORGANIZATION_TYPE = 'company';
DELETE FROM SK_PROPERTY_REL_ORG WHERE PROPERTY_ID = 'ERP2Mall_Stop_Mail_Sales_Rep' AND ORGANIZATION_TYPE = 'company';
DELETE FROM SK_PROPERTY_REL_ORG WHERE PROPERTY_ID = 'ERP2Mall_Stop_Mail_Cust_Contact' AND ORGANIZATION_TYPE = 'company';
DELETE FROM SK_PROPERTY_REL_ORG WHERE PROPERTY_ID = 'Order_Acknowledgement_Email_List_View' AND ORGANIZATION_TYPE = 'company';
DELETE FROM SK_PROPERTY_REL_ORG WHERE PROPERTY_ID = 'Display_Payment_Terms_Order_Mamt' AND ORGANIZATION_TYPE = 'company';
DELETE FROM SK_PROPERTY_REL_ORG WHERE PROPERTY_ID = 'Chat_Logged-In-User' AND ORGANIZATION_TYPE = 'company';
DELETE FROM SK_PROPERTY_REL_ORG WHERE PROPERTY_ID = 'Callback_Logged-In-User' AND ORGANIZATION_TYPE = 'company';

COMMIT;