/***
*** Requester Name:  	Alok Bansal
*** Purpose :		Cart Performance issue
*** Schema  :		atgcore
*** Date of Request : 	Sep 28, 2017
***/


ALTER TABLE SK_AMOUNT_INFO DROP CONSTRAINT SK_AMT_INFO_PK;
ALTER TABLE SK_ITEM_PRICE DROP CONSTRAINT SK_ITEM_PRICE_PK;
ALTER TABLE SK_DISCOUNT DROP CONSTRAINT SK_DISCOUNT_PK;
ALTER TABLE SK_METAL_SURCHARGES DROP CONSTRAINT SK_METAL_SUR_PK;
ALTER TABLE SK_ORDER DROP CONSTRAINT SK_ORDER_PK;
ALTER TABLE SK_ORDER_PRICEINFO DROP CONSTRAINT SK_ORDER_PRICEINFO_PK;
ALTER TABLE SK_SW_ITEM DROP CONSTRAINT SK_SW_ITEM_PK;







