CREATE TABLE SK_ORG_ADDRESS (
	ORG_ID 		VARCHAR2(40)	NOT NULL REFERENCES DPS_ORGANIZATION(ORG_ID),
	TAG 		NUMBER(38,0)	NOT NULL,
	ADDR_ID 	VARCHAR2(40)	NULL REFERENCES DPS_CONTACT_INFO(ID),
	PRIMARY KEY(ORG_ID, TAG)
);

INSERT INTO SK_ORG_ADDRESS (ORG_ID, TAG, ADDR_ID) SELECT ORG_ID, TAG, ADDR_ID FROM DCS_ORG_ADDRESS;

commit;