/***
*** Requester Name:  	Swaminath Chengannagari
*** Purpose :		 	SK-41034
*** Schema  :		 	atgcore
*** Date of Request : 	May 10, 2017
***/

INSERT INTO SK_PROPERTY (PROPERTY_ID,PROPERTY_NAME,PROPERTY_DISPLAY_NAME,PROPERTY_DESCRIPTION,DEFAULT_VALUE,ENABLE,PROPERTY_TYPE, GROUP_ID,COMPONENT_ID)
VALUES('Display_Payment_Terms_Order_Mamt','Display payment terms','Display payment terms','Display payment terms','Display payment terms',1,'Boolean','Cart_Display','ATG');


INSERT INTO SK_ORG_PROPERTY(ID,PROPERTY_ID,VERSION,RELATIVE_TO)
VALUES(
'601_Disp_Pay_Trms',
'Display_Payment_Terms_Order_Mamt',
1,
'600001'
);

INSERT INTO SK_ORG_PROPERTY(ID,PROPERTY_ID,VERSION,RELATIVE_TO)
VALUES(
'202_Disp_Pay_Trms',
'Display_Payment_Terms_Order_Mamt',
1,
'200002'
);

INSERT INTO SK_ORG_PROPERTY(ID,PROPERTY_ID,VERSION,RELATIVE_TO)
VALUES(
'403_Disp_Pay_Trms',
'Display_Payment_Terms_Order_Mamt',
1,
'400003'
);

INSERT INTO SK_ORG_PROPERTY(ID,PROPERTY_ID,VERSION,RELATIVE_TO)
VALUES(
'303_Disp_Pay_Trms',
'Display_Payment_Terms_Order_Mamt',
1,
'300003'
);

INSERT INTO SK_ORG_PROPERTY(ID,PROPERTY_ID,VERSION,RELATIVE_TO)
VALUES(
'404_Disp_Pay_Trms',
'Display_Payment_Terms_Order_Mamt',
1,
'400004'
);

INSERT INTO SK_ORG_PROPERTY(ID,PROPERTY_ID,VERSION,RELATIVE_TO)
VALUES(
'101_Disp_Pay_Trms',
'Display_Payment_Terms_Order_Mamt',
1,
'100001'
);

INSERT INTO SK_ORG_PROPERTY(ID,PROPERTY_ID,VERSION,RELATIVE_TO)
VALUES(
'401_Disp_Pay_Trms',
'Display_Payment_Terms_Order_Mamt',
1,
'400001'
);

INSERT INTO SK_ORG_PROPERTY(ID,PROPERTY_ID,VERSION,RELATIVE_TO)
VALUES(
'402_Disp_Pay_Trms',
'Display_Payment_Terms_Order_Mamt',
1,
'400002'
);

INSERT INTO SK_ORG_PROPERTY(ID,PROPERTY_ID,VERSION,RELATIVE_TO)
VALUES(
'102_Disp_Pay_Trms',
'Display_Payment_Terms_Order_Mamt',
1,
'100002'
);

INSERT INTO SK_ORG_PROPERTY(ID,PROPERTY_ID,VERSION,RELATIVE_TO)
VALUES(
'103_Disp_Pay_Trms',
'Display_Payment_Terms_Order_Mamt',
1,
'100003'
);

INSERT INTO SK_ORG_PROPERTY(ID,PROPERTY_ID,VERSION,RELATIVE_TO)
VALUES(
'104_Disp_Pay_Trms',
'Display_Payment_Terms_Order_Mamt',
1,
'100004'
);

INSERT INTO SK_ORG_PROPERTY(ID,PROPERTY_ID,VERSION,RELATIVE_TO)
VALUES(
'301_Disp_Pay_Trms',
'Display_Payment_Terms_Order_Mamt',
1,
'300001'
);

INSERT INTO SK_ORG_PROPERTY(ID,PROPERTY_ID,VERSION,RELATIVE_TO)
VALUES(
'302_Disp_Pay_Trms',
'Display_Payment_Terms_Order_Mamt',
1,
'300002'
);

INSERT INTO SK_ORG_PROPERTY(ID,PROPERTY_ID,VERSION,RELATIVE_TO)
VALUES(
'203_Disp_Pay_Trms',
'Display_Payment_Terms_Order_Mamt',
1,
'200003'
);

INSERT INTO SK_ORG_PROPERTY(ID,PROPERTY_ID,VERSION,RELATIVE_TO)
VALUES(
'201_Disp_Pay_Trms',
'Display_Payment_Terms_Order_Mamt',
1,
'200001'
);

INSERT INTO SK_ORG_PROPERTY(ID,PROPERTY_ID,VERSION,RELATIVE_TO)
VALUES(
't02_Disp_Pay_Trms',
'Display_Payment_Terms_Order_Mamt',
1,
't02239'
);

INSERT INTO SK_ORG_SETTINGS(ID,ORG_SETTING_ID) VALUES('600001','601_Disp_Pay_Trms');
INSERT INTO SK_ORG_SETTINGS(ID,ORG_SETTING_ID) VALUES('200002','202_Disp_Pay_Trms');
INSERT INTO SK_ORG_SETTINGS(ID,ORG_SETTING_ID) VALUES('400003','403_Disp_Pay_Trms');
INSERT INTO SK_ORG_SETTINGS(ID,ORG_SETTING_ID) VALUES('300003','303_Disp_Pay_Trms');
INSERT INTO SK_ORG_SETTINGS(ID,ORG_SETTING_ID) VALUES('400004','404_Disp_Pay_Trms');
INSERT INTO SK_ORG_SETTINGS(ID,ORG_SETTING_ID) VALUES('100001','101_Disp_Pay_Trms');
INSERT INTO SK_ORG_SETTINGS(ID,ORG_SETTING_ID) VALUES('400001','401_Disp_Pay_Trms');
INSERT INTO SK_ORG_SETTINGS(ID,ORG_SETTING_ID) VALUES('400002','402_Disp_Pay_Trms');
INSERT INTO SK_ORG_SETTINGS(ID,ORG_SETTING_ID) VALUES('100002','102_Disp_Pay_Trms');
INSERT INTO SK_ORG_SETTINGS(ID,ORG_SETTING_ID) VALUES('100003','103_Disp_Pay_Trms');
INSERT INTO SK_ORG_SETTINGS(ID,ORG_SETTING_ID) VALUES('100004','104_Disp_Pay_Trms');
INSERT INTO SK_ORG_SETTINGS(ID,ORG_SETTING_ID) VALUES('300001','301_Disp_Pay_Trms');
INSERT INTO SK_ORG_SETTINGS(ID,ORG_SETTING_ID) VALUES('300002','302_Disp_Pay_Trms');
INSERT INTO SK_ORG_SETTINGS(ID,ORG_SETTING_ID) VALUES('200003','203_Disp_Pay_Trms');
INSERT INTO SK_ORG_SETTINGS(ID,ORG_SETTING_ID) VALUES('200001','201_Disp_Pay_Trms');
INSERT INTO SK_ORG_SETTINGS(ID,ORG_SETTING_ID) VALUES('t02239','t02_Disp_Pay_Trms');

COMMIT;