-- /***
-- *** Requester Name:  Jyoti Sankar
-- *** Purpose : Tables SK_SD_KANLIST_RESP, SK_SD_RECP_KANLISTS, SK_SD_COMP_KANLISTS;
-- *** Schema  : SMSR.CORE.CI
-- *** Date of Request : 18/04/2017
-- ***/ --
-- Create new Table SK_SD_KANLIST_RESP --
CREATE TABLE SK_SD_KANLIST_RESP (
	id 			varchar2(254)	NOT NULL,
	KAN_GROUP 	varchar2(254)	NULL,
	KAN_NAME 		varchar2(254)	NULL,
	KAN_SPROG 	varchar2(254)	NULL,
	KAN_STATUS 	varchar2(254)	NULL,
	CONSTRAINT SK_SD_KANLIST_RESP_PK PRIMARY KEY(id)
);

-- Create new Table SK_SD_RECP_KANLISTS --
CREATE TABLE SK_SD_RECP_KANLISTS (
	LOG_ID 			varchar2(254)	NOT NULL REFERENCES SK_SD_SOFTWARE_INFO(LOG_ID),
	RECIP_KANLIST_ID 	varchar2(254)	NOT NULL REFERENCES SK_SD_KANLIST_RESP(id),
	CONSTRAINT SK_SD_RECP_KANLISTS_PK PRIMARY KEY(LOG_ID, RECIP_KANLIST_ID)
);

-- Create new Table SK_SD_COMP_KANLISTS --
CREATE TABLE SK_SD_COMP_KANLISTS (
	LOG_ID 			varchar2(254)	NOT NULL REFERENCES SK_SD_SOFTWARE_INFO(LOG_ID),
	COMP_KANLIST_ID 	varchar2(254)	NOT NULL REFERENCES SK_SD_KANLIST_RESP(id),
	CONSTRAINT SK_SD_COMP_KANLISTS_PK PRIMARY KEY(LOG_ID, COMP_KANLIST_ID)
);