/***
*** Requester Name:  Alok Bansal
*** Purpose : SQL for adding Columns in SK_ITEM_PRICE and SK_ORDER_PRICEINFO
*** Schema  : Core/Staging
*** Date of Request : 19/05/2017
***/

ALTER TABLE SK_ITEM_PRICE ADD (QUOTE_GALP_VALUE NUMBER(19) );

ALTER TABLE SK_ITEM_PRICE ADD (QUOTE_GALP_CURRENCY VARCHAR2(50) );

ALTER TABLE SK_ITEM_PRICE ADD (QCP_VALUE NUMBER(19) );

ALTER TABLE SK_ITEM_PRICE ADD (QCP_CURRENCY VARCHAR2(50) );

ALTER TABLE SK_ITEM_PRICE ADD (QUOTE_MARGIN NUMBER(19) );



ALTER TABLE SK_ORDER_PRICEINFO ADD (GALPT_VALUE NUMBER(19) );

ALTER TABLE SK_ORDER_PRICEINFO ADD (GALPT_CURRENCY VARCHAR2(50) );

ALTER TABLE SK_ORDER_PRICEINFO ADD (GAQPT_VALUE NUMBER(19) );

ALTER TABLE SK_ORDER_PRICEINFO ADD (GAQPT_CURRENCY VARCHAR2(50) );

ALTER TABLE SK_ORDER_PRICEINFO ADD (QUOTE_MARGIN_TOTAL NUMBER(19) );