/***
*** Requester Name:  	Swaminath Chengannagari
*** Purpose :		 	SK-50195
*** Schema  :		 	atgcore
*** Date of Request : 	April 27, 2017
***/


INSERT INTO SK_PROPERTY_REL_ORG (PROPERTY_ID,ORGANIZATION_TYPE) VALUES ('Certified_Partner','company');
INSERT INTO SK_PROPERTY_REL_ORG (PROPERTY_ID,ORGANIZATION_TYPE) VALUES ('Is_MC_Company','company');
INSERT INTO SK_PROPERTY_REL_ORG (PROPERTY_ID,ORGANIZATION_TYPE) VALUES ('List_Price_Type','company');
INSERT INTO SK_PROPERTY_REL_ORG (PROPERTY_ID,ORGANIZATION_TYPE) VALUES ('Show_Discount','company');
INSERT INTO SK_PROPERTY_REL_ORG (PROPERTY_ID,ORGANIZATION_TYPE) VALUES ('Show_Customer_Price','company');
INSERT INTO SK_PROPERTY_REL_ORG (PROPERTY_ID,ORGANIZATION_TYPE) VALUES ('Create_Quote','company');
INSERT INTO SK_PROPERTY_REL_ORG (PROPERTY_ID,ORGANIZATION_TYPE) VALUES ('Allow_Editing_Of_Price','company');
INSERT INTO SK_PROPERTY_REL_ORG (PROPERTY_ID,ORGANIZATION_TYPE) VALUES ('Allow_Editing_Of_Quote','company');
INSERT INTO SK_PROPERTY_REL_ORG (PROPERTY_ID,ORGANIZATION_TYPE) VALUES ('oci_cxml_profile','company');
INSERT INTO SK_PROPERTY_REL_ORG (PROPERTY_ID,ORGANIZATION_TYPE) VALUES ('ERP2Mall_Stop_Options','company');
INSERT INTO SK_PROPERTY_REL_ORG (PROPERTY_ID,ORGANIZATION_TYPE) VALUES ('SO_Article_Not_Found','company');
INSERT INTO SK_PROPERTY_REL_ORG (PROPERTY_ID,ORGANIZATION_TYPE) VALUES ('E2M_Order_Contains_SN_Product','company');
INSERT INTO SK_PROPERTY_REL_ORG (PROPERTY_ID,ORGANIZATION_TYPE) VALUES ('Stop_In_Case_of_Software_Product','company');
INSERT INTO SK_PROPERTY_REL_ORG (PROPERTY_ID,ORGANIZATION_TYPE) VALUES ('SO_Different_Price','company');
INSERT INTO SK_PROPERTY_REL_ORG (PROPERTY_ID,ORGANIZATION_TYPE) VALUES ('SO_Request_Delivery_Date_Not_Possible','company');
INSERT INTO SK_PROPERTY_REL_ORG (PROPERTY_ID,ORGANIZATION_TYPE) VALUES ('SO_Invalid_SPA_Number','company');
INSERT INTO SK_PROPERTY_REL_ORG (PROPERTY_ID,ORGANIZATION_TYPE) VALUES ('SO_Available_Successor_Part_Number','company');
INSERT INTO SK_PROPERTY_REL_ORG (PROPERTY_ID,ORGANIZATION_TYPE) VALUES ('SO_Min_Order_Quantity_Not_Achieved','company');
INSERT INTO SK_PROPERTY_REL_ORG (PROPERTY_ID,ORGANIZATION_TYPE) VALUES ('SO_Min_Order_Value_Not_Exceeded','company');
INSERT INTO SK_PROPERTY_REL_ORG (PROPERTY_ID,ORGANIZATION_TYPE) VALUES ('ERP2Mall_Stop_Mail_Sales_Rep','company');
INSERT INTO SK_PROPERTY_REL_ORG (PROPERTY_ID,ORGANIZATION_TYPE) VALUES ('ERP2Mall_Stop_Mail_Cust_Contact','company');
INSERT INTO SK_PROPERTY_REL_ORG (PROPERTY_ID,ORGANIZATION_TYPE) VALUES ('Order_Acknowledgement_Email_List_View','company');
INSERT INTO SK_PROPERTY_REL_ORG (PROPERTY_ID,ORGANIZATION_TYPE) VALUES ('Display_Payment_Terms_Order_Mamt','company');
INSERT INTO SK_PROPERTY_REL_ORG (PROPERTY_ID,ORGANIZATION_TYPE) VALUES ('Chat_Logged-In-User','company');
INSERT INTO SK_PROPERTY_REL_ORG (PROPERTY_ID,ORGANIZATION_TYPE) VALUES ('Callback_Logged-In-User','company');

COMMIT;