/***
*** Requester Name:  	Alok Bansal
*** Purpose :		Cart Performance issue
*** Schema  :		atgcore
*** Date of Request : 	Sep 28, 2017
***/


ALTER TABLE SK_AMOUNT_INFO ADD CONSTRAINT SK_AMT_INFO_PK PRIMARY KEY (AMOUNT_INFO_ID);
ALTER TABLE SK_ITEM_PRICE ADD CONSTRAINT SK_ITEM_PRICE_PK PRIMARY KEY (AMOUNT_INFO_ID);
ALTER TABLE SK_DISCOUNT ADD CONSTRAINT SK_DISCOUNT_PK PRIMARY KEY (AMOUNT_INFO_ID);
ALTER TABLE SK_METAL_SURCHARGES ADD CONSTRAINT SK_METAL_SUR_PK PRIMARY KEY (AMOUNT_INFO_ID);
ALTER TABLE SK_ORDER ADD CONSTRAINT SK_ORDER_PK PRIMARY KEY (ORDER_ID);
ALTER TABLE SK_ORDER_PRICEINFO ADD CONSTRAINT SK_ORDER_PRICEINFO_PK PRIMARY KEY (AMOUNT_INFO_ID);
ALTER TABLE SK_SW_ITEM ADD CONSTRAINT SK_SW_ITEM_PK PRIMARY KEY (COMMERCE_ITEM_ID);







