insert into sk_ibase_auxilary_data values ('40001','AF','Afghanistan',4);
insert into sk_ibase_auxilary_data values ('40002','AX','Aland Islands',4);
insert into sk_ibase_auxilary_data values ('40003','AL','Albania',4);
insert into sk_ibase_auxilary_data values ('40004','DZ','Algeria',4);
insert into sk_ibase_auxilary_data values ('40005','AS','American Samoa',4);
insert into sk_ibase_auxilary_data values ('40006','AD','Andorra',4);
insert into sk_ibase_auxilary_data values ('40007','AO','Angola',4);
insert into sk_ibase_auxilary_data values ('40008','AI','Anguilla',4);
insert into sk_ibase_auxilary_data values ('40009','AQ','Antarctica',4);
insert into sk_ibase_auxilary_data values ('40010','AG','Antigua and Barbuda',4);
insert into sk_ibase_auxilary_data values ('40011','AR','Argentina',4);
insert into sk_ibase_auxilary_data values ('40012','AM','Armenia',4);
insert into sk_ibase_auxilary_data values ('40013','AW','Aruba',4);
insert into sk_ibase_auxilary_data values ('40014','AU','Australia',4);
insert into sk_ibase_auxilary_data values ('40015','AT','Austria',4);
insert into sk_ibase_auxilary_data values ('40016','AZ','Azerbaijan',4);
insert into sk_ibase_auxilary_data values ('40017','BS','Bahamas',4);
insert into sk_ibase_auxilary_data values ('40018','BH','Bahrain',4);
insert into sk_ibase_auxilary_data values ('40019','BD','Bangladesh',4);
insert into sk_ibase_auxilary_data values ('40020','BB','Barbados',4);
insert into sk_ibase_auxilary_data values ('40021','BY','Belarus',4);
insert into sk_ibase_auxilary_data values ('40022','BE','Belgium',4);
insert into sk_ibase_auxilary_data values ('40023','BZ','Belize',4);
insert into sk_ibase_auxilary_data values ('40024','BJ','Benin',4);
insert into sk_ibase_auxilary_data values ('40025','BM','Bermuda',4);
insert into sk_ibase_auxilary_data values ('40026','BT','Bhutan',4);
insert into sk_ibase_auxilary_data values ('40027','BO','Bolivia, Plurinational State of',4);
insert into sk_ibase_auxilary_data values ('40028','BQ','Bonaire, Saint Eustatius and Saba',4);
insert into sk_ibase_auxilary_data values ('40029','BA','Bosnia and Herzegovina',4);
insert into sk_ibase_auxilary_data values ('40030','BW','Botswana',4);
insert into sk_ibase_auxilary_data values ('40031','BV','Bouvet Island',4);
insert into sk_ibase_auxilary_data values ('40032','BR','Brazil',4);
insert into sk_ibase_auxilary_data values ('40033','IO','British Indian Ocean Territory',4);
insert into sk_ibase_auxilary_data values ('40034','BN','Brunei Darussalam',4);
insert into sk_ibase_auxilary_data values ('40035','BG','Bulgaria',4);
insert into sk_ibase_auxilary_data values ('40036','BF','Burkina Faso',4);
insert into sk_ibase_auxilary_data values ('40037','BI','Burundi',4);
insert into sk_ibase_auxilary_data values ('40038','KH','Cambodia',4);
insert into sk_ibase_auxilary_data values ('40039','CM','Cameroon',4);
insert into sk_ibase_auxilary_data values ('40040','CA','Canada',4);
insert into sk_ibase_auxilary_data values ('40041','CV','Cape Verde',4);
insert into sk_ibase_auxilary_data values ('40042','KY','Cayman Islands',4);
insert into sk_ibase_auxilary_data values ('40043','CF','Central African Republic',4);
insert into sk_ibase_auxilary_data values ('40044','TD','Chad',4);
insert into sk_ibase_auxilary_data values ('40045','CL','Chile',4);
insert into sk_ibase_auxilary_data values ('40046','CN','China',4);
insert into sk_ibase_auxilary_data values ('40047','CX','Christmas Island',4);
insert into sk_ibase_auxilary_data values ('40048','CC','Cocos (Keeling) Islands',4);
insert into sk_ibase_auxilary_data values ('40049','CO','Colombia',4);
insert into sk_ibase_auxilary_data values ('40050','KM','Comoros',4);
insert into sk_ibase_auxilary_data values ('40051','CG','Congo',4);
insert into sk_ibase_auxilary_data values ('40052','CD','Congo, the democratic Republic of the',4);
insert into sk_ibase_auxilary_data values ('40053','CK','Cook Islands',4);
insert into sk_ibase_auxilary_data values ('40054','CR','Costa Rica',4);
insert into sk_ibase_auxilary_data values ('40055','CI','Cote d''Ivoire',4);
insert into sk_ibase_auxilary_data values ('40056','HR','Croatia',4);
insert into sk_ibase_auxilary_data values ('40057','CU','Cuba',4);
insert into sk_ibase_auxilary_data values ('40058','CW','Curaçao',4);
insert into sk_ibase_auxilary_data values ('40059','CY','Cyprus',4);
insert into sk_ibase_auxilary_data values ('40060','CZ','Czechia',4);
insert into sk_ibase_auxilary_data values ('40061','DK','Denmark',4);
insert into sk_ibase_auxilary_data values ('40062','DJ','Djibouti',4);
insert into sk_ibase_auxilary_data values ('40063','DM','Dominica',4);
insert into sk_ibase_auxilary_data values ('40064','DO','Dominican Republic',4);
insert into sk_ibase_auxilary_data values ('40065','EC','Ecuador',4);
insert into sk_ibase_auxilary_data values ('40066','EG','Egypt',4);
insert into sk_ibase_auxilary_data values ('40067','SV','El Salvador',4);
insert into sk_ibase_auxilary_data values ('40068','GQ','Equatorial Guinea',4);
insert into sk_ibase_auxilary_data values ('40069','ER','Eritrea',4);
insert into sk_ibase_auxilary_data values ('40070','EE','Estonia',4);
insert into sk_ibase_auxilary_data values ('40071','ET','Ethiopia',4);
insert into sk_ibase_auxilary_data values ('40072','FK','Falkland Islands (Malvinas)',4);
insert into sk_ibase_auxilary_data values ('40073','FO','Faroe Islands',4);
insert into sk_ibase_auxilary_data values ('40074','FJ','Fiji',4);
insert into sk_ibase_auxilary_data values ('40075','FI','Finland',4);
insert into sk_ibase_auxilary_data values ('40076','FR','France',4);
insert into sk_ibase_auxilary_data values ('40077','GF','French Guiana',4);
insert into sk_ibase_auxilary_data values ('40078','PF','French Polynesia',4);
insert into sk_ibase_auxilary_data values ('40079','TF','French Southern Territories',4);
insert into sk_ibase_auxilary_data values ('40080','GA','Gabon',4);
insert into sk_ibase_auxilary_data values ('40081','GM','Gambia',4);
insert into sk_ibase_auxilary_data values ('40082','GE','Georgia',4);
insert into sk_ibase_auxilary_data values ('40083','DE','Germany',4);
insert into sk_ibase_auxilary_data values ('40084','GH','Ghana',4);
insert into sk_ibase_auxilary_data values ('40085','GI','Gibraltar',4);
insert into sk_ibase_auxilary_data values ('40086','GR','Greece',4);
insert into sk_ibase_auxilary_data values ('40087','GL','Greenland',4);
insert into sk_ibase_auxilary_data values ('40088','GD','Grenada',4);
insert into sk_ibase_auxilary_data values ('40089','GP','Guadeloupe',4);
insert into sk_ibase_auxilary_data values ('40090','GU','Guam',4);
insert into sk_ibase_auxilary_data values ('40091','GT','Guatemala',4);
insert into sk_ibase_auxilary_data values ('40092','GG','Guernsey',4);
insert into sk_ibase_auxilary_data values ('40093','GN','Guinea',4);
insert into sk_ibase_auxilary_data values ('40094','GW','Guinea-Bissau',4);
insert into sk_ibase_auxilary_data values ('40095','GY','Guyana',4);
insert into sk_ibase_auxilary_data values ('40096','HT','Haiti',4);
insert into sk_ibase_auxilary_data values ('40097','HM','Heard Island and McDonald Islands',4);
insert into sk_ibase_auxilary_data values ('40098','VA','Holy see (Vatican City State)',4);
insert into sk_ibase_auxilary_data values ('40099','HN','Honduras',4);
insert into sk_ibase_auxilary_data values ('40100','HK','Hong Kong',4);
insert into sk_ibase_auxilary_data values ('40101','HU','Hungary',4);
insert into sk_ibase_auxilary_data values ('40102','IS','Iceland',4);
insert into sk_ibase_auxilary_data values ('40103','IN','India',4);
insert into sk_ibase_auxilary_data values ('40104','ID','Indonesia',4);
insert into sk_ibase_auxilary_data values ('40105','IR','Iran, Islamic Republic of',4);
insert into sk_ibase_auxilary_data values ('40106','IQ','Iraq',4);
insert into sk_ibase_auxilary_data values ('40107','IE','Ireland',4);
insert into sk_ibase_auxilary_data values ('40108','IM','Isle of Man',4);
insert into sk_ibase_auxilary_data values ('40109','IL','Israel',4);
insert into sk_ibase_auxilary_data values ('40110','IT','Italy',4);
insert into sk_ibase_auxilary_data values ('40111','JM','Jamaica',4);
insert into sk_ibase_auxilary_data values ('40112','JP','Japan',4);
insert into sk_ibase_auxilary_data values ('40113','JE','Jersey',4);
insert into sk_ibase_auxilary_data values ('40114','JO','Jordan',4);
insert into sk_ibase_auxilary_data values ('40115','KZ','Kazakhstan',4);
insert into sk_ibase_auxilary_data values ('40116','KE','Kenya',4);
insert into sk_ibase_auxilary_data values ('40117','KI','Kiribati',4);
insert into sk_ibase_auxilary_data values ('40118','KP','Korea, Democratic People''s Republic of',4);
insert into sk_ibase_auxilary_data values ('40119','KR','Korea, Republic of',4);
insert into sk_ibase_auxilary_data values ('40120','KW','Kuwait',4);
insert into sk_ibase_auxilary_data values ('40121','KG','Kyrgyzstan',4);
insert into sk_ibase_auxilary_data values ('40122','LA','Lao people''s democratic republic',4);
insert into sk_ibase_auxilary_data values ('40123','LV','Latvia',4);
insert into sk_ibase_auxilary_data values ('40124','LB','Lebanon',4);
insert into sk_ibase_auxilary_data values ('40125','LS','Lesotho',4);
insert into sk_ibase_auxilary_data values ('40126','LR','Liberia',4);
insert into sk_ibase_auxilary_data values ('40127','LY','Libya',4);
insert into sk_ibase_auxilary_data values ('40128','LI','Liechtenstein',4);
insert into sk_ibase_auxilary_data values ('40129','LT','Lithuania',4);
insert into sk_ibase_auxilary_data values ('40130','LU','Luxembourg',4);
insert into sk_ibase_auxilary_data values ('40131','MO','Macao',4);
insert into sk_ibase_auxilary_data values ('40132','MK','Macedonia, the former yugoslav Republic of',4);
insert into sk_ibase_auxilary_data values ('40133','MG','Madagascar',4);
insert into sk_ibase_auxilary_data values ('40134','MW','Malawi',4);
insert into sk_ibase_auxilary_data values ('40135','MY','Malaysia',4);
insert into sk_ibase_auxilary_data values ('40136','MV','Maldives',4);
insert into sk_ibase_auxilary_data values ('40137','ML','Mali',4);
insert into sk_ibase_auxilary_data values ('40138','MT','Malta',4);
insert into sk_ibase_auxilary_data values ('40139','MH','Marshall Islands',4);
insert into sk_ibase_auxilary_data values ('40140','MQ','Martinique',4);
insert into sk_ibase_auxilary_data values ('40141','MR','Mauritania',4);
insert into sk_ibase_auxilary_data values ('40142','MU','Mauritius',4);
insert into sk_ibase_auxilary_data values ('40143','YT','Mayotte',4);
insert into sk_ibase_auxilary_data values ('40144','MX','Mexico',4);
insert into sk_ibase_auxilary_data values ('40145','FM','Micronesia, Federated States of',4);
insert into sk_ibase_auxilary_data values ('40146','MD','Moldova, Republic of',4);
insert into sk_ibase_auxilary_data values ('40147','MC','Monaco',4);
insert into sk_ibase_auxilary_data values ('40148','MN','Mongolia',4);
insert into sk_ibase_auxilary_data values ('40149','ME','Montenegro',4);
insert into sk_ibase_auxilary_data values ('40150','MS','Montserrat',4);
insert into sk_ibase_auxilary_data values ('40151','MA','Morocco',4);
insert into sk_ibase_auxilary_data values ('40152','MZ','Mozambique',4);
insert into sk_ibase_auxilary_data values ('40153','MM','Myanmar',4);
insert into sk_ibase_auxilary_data values ('40154','NA','Namibia',4);
insert into sk_ibase_auxilary_data values ('40155','NR','Nauru',4);
insert into sk_ibase_auxilary_data values ('40156','NP','Nepal',4);
insert into sk_ibase_auxilary_data values ('40157','NL','Netherlands',4);
insert into sk_ibase_auxilary_data values ('40158','AN','Netherlands Antilles',4);
insert into sk_ibase_auxilary_data values ('40159','NC','New Caledonia',4);
insert into sk_ibase_auxilary_data values ('40160','NZ','New Zealand',4);
insert into sk_ibase_auxilary_data values ('40161','NI','Nicaragua',4);
insert into sk_ibase_auxilary_data values ('40162','NE','Niger',4);
insert into sk_ibase_auxilary_data values ('40163','NG','Nigeria',4);
insert into sk_ibase_auxilary_data values ('40164','NU','Niue',4);
insert into sk_ibase_auxilary_data values ('40165','NF','Norfolk Island',4);
insert into sk_ibase_auxilary_data values ('40166','MP','Northern Mariana Islands',4);
insert into sk_ibase_auxilary_data values ('40167','NO','Norway',4);
insert into sk_ibase_auxilary_data values ('40168','OM','Oman',4);
insert into sk_ibase_auxilary_data values ('40169','PK','Pakistan',4);
insert into sk_ibase_auxilary_data values ('40170','PW','Palau',4);
insert into sk_ibase_auxilary_data values ('40171','PS','Palestine, State of',4);
insert into sk_ibase_auxilary_data values ('40172','PA','Panama',4);
insert into sk_ibase_auxilary_data values ('40173','PD','Pandomia',4);
insert into sk_ibase_auxilary_data values ('40174','PG','Papua New Guinea',4);
insert into sk_ibase_auxilary_data values ('40175','PY','Paraguay',4);
insert into sk_ibase_auxilary_data values ('40176','PE','Peru',4);
insert into sk_ibase_auxilary_data values ('40177','PH','Philippines',4);
insert into sk_ibase_auxilary_data values ('40178','PN','Pitcairn',4);
insert into sk_ibase_auxilary_data values ('40179','PL','Poland',4);
insert into sk_ibase_auxilary_data values ('40180','PT','Portugal',4);
insert into sk_ibase_auxilary_data values ('40181','PR','Puerto Rico',4);
insert into sk_ibase_auxilary_data values ('40182','QA','Qatar',4);
insert into sk_ibase_auxilary_data values ('40183','RE','Reunion',4);
insert into sk_ibase_auxilary_data values ('40184','RO','Romania',4);
insert into sk_ibase_auxilary_data values ('40185','RU','Russian Federation',4);
insert into sk_ibase_auxilary_data values ('40186','RW','Rwanda',4);
insert into sk_ibase_auxilary_data values ('40187','BL','Saint Barthelemy',4);
insert into sk_ibase_auxilary_data values ('40188','SH','Saint Helena, Ascension and Tristan da Cunha',4);
insert into sk_ibase_auxilary_data values ('40189','KN','Saint Kitts and Nevis',4);
insert into sk_ibase_auxilary_data values ('40190','LC','Saint Lucia',4);
insert into sk_ibase_auxilary_data values ('40191','MF','Saint Martin',4);
insert into sk_ibase_auxilary_data values ('40192','PM','Saint Pierre and Miquelon',4);
insert into sk_ibase_auxilary_data values ('40193','VC','Saint Vincent and the Grenadines',4);
insert into sk_ibase_auxilary_data values ('40194','WS','Samoa',4);
insert into sk_ibase_auxilary_data values ('40195','SM','San Marino',4);
insert into sk_ibase_auxilary_data values ('40196','ST','Sao Tome and Principe',4);
insert into sk_ibase_auxilary_data values ('40197','SA','Saudi Arabia',4);
insert into sk_ibase_auxilary_data values ('40198','SN','Senegal',4);
insert into sk_ibase_auxilary_data values ('40199','SU','Sentaria',4);
insert into sk_ibase_auxilary_data values ('40200','RS','Serbia',4);
insert into sk_ibase_auxilary_data values ('40201','SC','Seychelles',4);
insert into sk_ibase_auxilary_data values ('40202','SL','Sierra Leone',4);
insert into sk_ibase_auxilary_data values ('40203','SG','Singapore',4);
insert into sk_ibase_auxilary_data values ('40204','SX','Sint Maarten (Dutch part)',4);
insert into sk_ibase_auxilary_data values ('40205','SK','Slovakia',4);
insert into sk_ibase_auxilary_data values ('40206','SI','Slovenia',4);
insert into sk_ibase_auxilary_data values ('40207','SB','Solomon Islands',4);
insert into sk_ibase_auxilary_data values ('40208','SO','Somalia',4);
insert into sk_ibase_auxilary_data values ('40209','ZA','South Africa',4);
insert into sk_ibase_auxilary_data values ('40210','GS','South Georgia and the South Sandwich Islands',4);
insert into sk_ibase_auxilary_data values ('40211','SS','South Sudan',4);
insert into sk_ibase_auxilary_data values ('40212','ES','Spain',4);
insert into sk_ibase_auxilary_data values ('40213','LK','Sri Lanka',4);
insert into sk_ibase_auxilary_data values ('40214','SD','Sudan',4);
insert into sk_ibase_auxilary_data values ('40215','SR','Suriname',4);
insert into sk_ibase_auxilary_data values ('40216','SJ','Svalbard and Jan Mayen',4);
insert into sk_ibase_auxilary_data values ('40217','SZ','Swaziland',4);
insert into sk_ibase_auxilary_data values ('40218','SE','Sweden',4);
insert into sk_ibase_auxilary_data values ('40219','CH','Switzerland',4);
insert into sk_ibase_auxilary_data values ('40220','SY','Syrian Arab Republic',4);
insert into sk_ibase_auxilary_data values ('40221','TW','Taiwan, Province of China',4);
insert into sk_ibase_auxilary_data values ('40222','TJ','Tajikistan',4);
insert into sk_ibase_auxilary_data values ('40223','TZ','Tanzania, United Republic of',4);
insert into sk_ibase_auxilary_data values ('40224','TLA','Tester Land A',4);
insert into sk_ibase_auxilary_data values ('40225','TLB','Tester Land B',4);
insert into sk_ibase_auxilary_data values ('40226','TLC','Tester Land C',4);
insert into sk_ibase_auxilary_data values ('40227','TLD','Tester Land D',4);
insert into sk_ibase_auxilary_data values ('40228','TLE','Tester Land E',4);
insert into sk_ibase_auxilary_data values ('40229','TLF','Tester Land F',4);
insert into sk_ibase_auxilary_data values ('40230','TH','Thailand',4);
insert into sk_ibase_auxilary_data values ('40231','TL','Timor-Leste',4);
insert into sk_ibase_auxilary_data values ('40232','TG','Togo',4);
insert into sk_ibase_auxilary_data values ('40233','TK','Tokelau',4);
insert into sk_ibase_auxilary_data values ('40234','TO','Tonga',4);
insert into sk_ibase_auxilary_data values ('40235','TT','Trinidad and Tobago',4);
insert into sk_ibase_auxilary_data values ('40236','TN','Tunisia',4);
insert into sk_ibase_auxilary_data values ('40237','TR','Turkey',4);
insert into sk_ibase_auxilary_data values ('40238','TM','Turkmenistan',4);
insert into sk_ibase_auxilary_data values ('40239','TC','Turks and Caicos Islands',4);
insert into sk_ibase_auxilary_data values ('40240','TV','Tuvalu',4);
insert into sk_ibase_auxilary_data values ('40241','UG','Uganda',4);
insert into sk_ibase_auxilary_data values ('40242','UA','Ukraine',4);
insert into sk_ibase_auxilary_data values ('40243','AE','United Arab Emirates',4);
insert into sk_ibase_auxilary_data values ('40244','GB','United Kingdom',4);
insert into sk_ibase_auxilary_data values ('40245','US','United States',4);
insert into sk_ibase_auxilary_data values ('40246','UM','United States Minor Outlying Islands',4);
insert into sk_ibase_auxilary_data values ('40247','UN','Unknown',4);
insert into sk_ibase_auxilary_data values ('40248','UY','Uruguay',4);
insert into sk_ibase_auxilary_data values ('40249','UZ','Uzbekistan',4);
insert into sk_ibase_auxilary_data values ('40250','VU','Vanuatu',4);
insert into sk_ibase_auxilary_data values ('40251','VE','Venezuela, Bolivarian Republic of',4);
insert into sk_ibase_auxilary_data values ('40252','VN','Viet Nam',4);
insert into sk_ibase_auxilary_data values ('40253','VG','Virgin Islands, British',4);
insert into sk_ibase_auxilary_data values ('40254','VI','Virgin Islands, U.S.',4);
insert into sk_ibase_auxilary_data values ('40255','WF','Wallis and Futuna',4);
insert into sk_ibase_auxilary_data values ('40256','EH','Western Sahara',4);
insert into sk_ibase_auxilary_data values ('40257','YE','Yemen',4);
insert into sk_ibase_auxilary_data values ('40258','ZM','Zambia',4);
insert into sk_ibase_auxilary_data values ('40259','ZW','Zimbabwe',4);


commit;