insert into sk_ibase_auxilary_data values ('20001','181','Getriebe-Technologien -> Aerators',2);
insert into sk_ibase_auxilary_data values ('20002','182','Getriebe-Technologien -> Agitators',2);
insert into sk_ibase_auxilary_data values ('20003','183','Getriebe-Technologien -> Air cooled condensers',2);
insert into sk_ibase_auxilary_data values ('20004','102','Allg. Antriebstechnologien',2);
insert into sk_ibase_auxilary_data values ('20005','184','Getriebe-Technologien -> Belt conveyors',2);
insert into sk_ibase_auxilary_data values ('20006','97','Bergbau-/Mining-Technologien',2);
insert into sk_ibase_auxilary_data values ('20007','173','Allg. Antriebstechnologien -> Broaching machine',2);
insert into sk_ibase_auxilary_data values ('20008','185','Getriebe-Technologien -> Bucket elevators',2);
insert into sk_ibase_auxilary_data values ('20009','186','Getriebe-Technologien -> Bucket wheel excavators',2);
insert into sk_ibase_auxilary_data values ('20010','166','Allg. Antriebstechnologien -> Centrifuges',2);
insert into sk_ibase_auxilary_data values ('20011','120','Papier- und Zellstoff-Technologien -> Chemical Pulp',2);
insert into sk_ibase_auxilary_data values ('20012','178','Allg. Antriebstechnologien -> Chiller',2);
insert into sk_ibase_auxilary_data values ('20013','121','Papier- und Zellstoff-Technologien -> Coater Technology',2);
insert into sk_ibase_auxilary_data values ('20014','107','Metall-/Metallurgie-Technologien -> Cold Rolling',2);
insert into sk_ibase_auxilary_data values ('20015','171','Allg. Antriebstechnologien -> Compressor',2);
insert into sk_ibase_auxilary_data values ('20016','108','Metall-/Metallurgie-Technologien -> Continuous Casting',2);
insert into sk_ibase_auxilary_data values ('20017','142','Motion Control, Production machines -> Converting',2);
insert into sk_ibase_auxilary_data values ('20018','112','Bergbau-/Mining-Technologien -> Conveyors',2);
insert into sk_ibase_auxilary_data values ('20019','187','Getriebe-Technologien -> Cranes',2);
insert into sk_ibase_auxilary_data values ('20020','188','Getriebe-Technologien -> Crushers',2);
insert into sk_ibase_auxilary_data values ('20021','174','Allg. Antriebstechnologien -> Cutting machine',2);
insert into sk_ibase_auxilary_data values ('20022','122','Papier- und Zellstoff-Technologien -> De-inked Pulp',2);
insert into sk_ibase_auxilary_data values ('20023','113','Bergbau-/Mining-Technologien -> Dragline '||chr(38)||' Shovels',2);
insert into sk_ibase_auxilary_data values ('20024','145','Motion Controls, Werkzeugmaschinen -> Drilling',2);
insert into sk_ibase_auxilary_data values ('20025','109','Metall-/Metallurgie-Technologien -> Endless Strip Production',2);
insert into sk_ibase_auxilary_data values ('20026','161','Motion Controls, Werkzeugmaschinen -> Eroding',2);
insert into sk_ibase_auxilary_data values ('20027','169','Allg. Antriebstechnologien -> Extruder',2);
insert into sk_ibase_auxilary_data values ('20028','189','Getriebe-Technologien -> Extruder',2);
insert into sk_ibase_auxilary_data values ('20029','175','Allg. Antriebstechnologien -> Fan',2);
insert into sk_ibase_auxilary_data values ('20030','114','Bergbau-/Mining-Technologien -> Filter Press',2);
insert into sk_ibase_auxilary_data values ('20031','105','Produktions-Automatisierung -> Flexible manufacturing system',2);
insert into sk_ibase_auxilary_data values ('20032','115','Bergbau-/Mining-Technologien -> Flotation',2);
insert into sk_ibase_auxilary_data values ('20033','146','Motion Controls, Werkzeugmaschinen -> Gear cutting',2);
insert into sk_ibase_auxilary_data values ('20034','104','Produktions-Automatisierung -> general',2);
insert into sk_ibase_auxilary_data values ('20035','106','Prozess-Automatisierung -> general',2);
insert into sk_ibase_auxilary_data values ('20036','103','Getriebe-Technologien',2);
insert into sk_ibase_auxilary_data values ('20037','135','Motion Control, Production machines -> Glas, Ceramic, Stone',2);
insert into sk_ibase_auxilary_data values ('20038','129','Motion Controls, Kräne und Hebezeuge -> Grab Ship Unloader (GSU)',2);
insert into sk_ibase_auxilary_data values ('20039','123','Papier- und Zellstoff-Technologien -> Graphic',2);
insert into sk_ibase_auxilary_data values ('20040','147','Motion Controls, Werkzeugmaschinen -> Grinding',2);
insert into sk_ibase_auxilary_data values ('20041','143','Motion Control, Production machines -> Handling',2);
insert into sk_ibase_auxilary_data values ('20042','148','Motion Controls, Werkzeugmaschinen -> Hobbing cutter',2);
insert into sk_ibase_auxilary_data values ('20043','149','Motion Controls, Werkzeugmaschinen -> Honing',2);
insert into sk_ibase_auxilary_data values ('20044','110','Metall-/Metallurgie-Technologien -> Hot Rolling Flat',2);
insert into sk_ibase_auxilary_data values ('20045','130','Motion Controls, Kräne und Hebezeuge -> Industrial Cranes',2);
insert into sk_ibase_auxilary_data values ('20046','190','Getriebe-Technologien -> Jack-Up Rigs',2);
insert into sk_ibase_auxilary_data values ('20047','150','Motion Controls, Werkzeugmaschinen -> Laser Cutting',2);
insert into sk_ibase_auxilary_data values ('20048','191','Getriebe-Technologien -> Lauter tuns',2);
insert into sk_ibase_auxilary_data values ('20049','144','Motion Control, Production machines -> Lightweight Construction',2);
insert into sk_ibase_auxilary_data values ('20050','151','Motion Controls, Werkzeugmaschinen -> Machining Center',2);
insert into sk_ibase_auxilary_data values ('20051','204','Getriebe-Technologien -> Marine/ships',2);
insert into sk_ibase_auxilary_data values ('20052','124','Papier- und Zellstoff-Technologien -> Mechanical Pulp',2);
insert into sk_ibase_auxilary_data values ('20053','140','Motion Control, Production machines -> Metal Forming',2);
insert into sk_ibase_auxilary_data values ('20054','96','Metall-/Metallurgie-Technologien',2);
insert into sk_ibase_auxilary_data values ('20055','177','Allg. Antriebstechnologien -> Mill',2);
insert into sk_ibase_auxilary_data values ('20056','152','Motion Controls, Werkzeugmaschinen -> Milling',2);
insert into sk_ibase_auxilary_data values ('20057','116','Bergbau-/Mining-Technologien -> Minewinder',2);
insert into sk_ibase_auxilary_data values ('20058','172','Allg. Antriebstechnologien -> Miscellaneous Pumps',2);
insert into sk_ibase_auxilary_data values ('20059','179','Allg. Antriebstechnologien -> Mixer',2);
insert into sk_ibase_auxilary_data values ('20060','100','Motion Control, Production machines',2);
insert into sk_ibase_auxilary_data values ('20061','99','Motion Controls, Kräne und Hebezeuge',2);
insert into sk_ibase_auxilary_data values ('20062','101','Motion Controls, Werkzeugmaschinen',2);
insert into sk_ibase_auxilary_data values ('20063','153','Motion Controls, Werkzeugmaschinen -> Nibbling',2);
insert into sk_ibase_auxilary_data values ('20064','180','Allg. Antriebstechnologien -> Oil'||chr(38)||'Gas',2);
insert into sk_ibase_auxilary_data values ('20065','212','Oxygenstahlwerk, Lichbogenofen, Pfannenofen',2);
insert into sk_ibase_auxilary_data values ('20066','131','Motion Control, Production machines -> Packaging',2);
insert into sk_ibase_auxilary_data values ('20067','192','Getriebe-Technologien -> Paper and pulp preparation sections',2);
insert into sk_ibase_auxilary_data values ('20068','98','Papier- und Zellstoff-Technologien',2);
insert into sk_ibase_auxilary_data values ('20069','154','Motion Controls, Werkzeugmaschinen -> Planing',2);
insert into sk_ibase_auxilary_data values ('20070','138','Motion Control, Production machines -> Plastics',2);
insert into sk_ibase_auxilary_data values ('20071','155','Motion Controls, Werkzeugmaschinen -> Polishing',2);
insert into sk_ibase_auxilary_data values ('20072','168','Allg. Antriebstechnologien -> Positioning',2);
insert into sk_ibase_auxilary_data values ('20073','164','Motion Controls, Werkzeugmaschinen -> Pressing, Bending and non-Cutting Machines',2);
insert into sk_ibase_auxilary_data values ('20074','132','Motion Control, Production machines -> Printing',2);
insert into sk_ibase_auxilary_data values ('20075','211','Motion Controls, Kräne und Hebezeuge -> Process Lines (Pickling Line, Galvanizing etc.)',2);
insert into sk_ibase_auxilary_data values ('20076','54','Produktions-Automatisierung',2);
insert into sk_ibase_auxilary_data values ('20077','53','Prozess-Automatisierung',2);
insert into sk_ibase_auxilary_data values ('20078','167','Allg. Antriebstechnologien -> Pump centrifugal',2);
insert into sk_ibase_auxilary_data values ('20079','117','Bergbau-/Mining-Technologien -> Pumps',2);
insert into sk_ibase_auxilary_data values ('20080','127','Motion Controls, Kräne und Hebezeuge -> Rail Mounted Gantry Cranes (RMG)',2);
insert into sk_ibase_auxilary_data values ('20081','193','Getriebe-Technologien -> Railway Vehicles',2);
insert into sk_ibase_auxilary_data values ('20082','194','Getriebe-Technologien -> Reactors',2);
insert into sk_ibase_auxilary_data values ('20083','159','Motion Controls, Werkzeugmaschinen -> Revolving transfer machine',2);
insert into sk_ibase_auxilary_data values ('20084','163','Motion Controls, Werkzeugmaschinen -> Robots and Manipulators',2);
insert into sk_ibase_auxilary_data values ('20085','195','Getriebe-Technologien -> Roller presses',2);
insert into sk_ibase_auxilary_data values ('20086','196','Getriebe-Technologien -> Ropeways',2);
insert into sk_ibase_auxilary_data values ('20087','197','Getriebe-Technologien -> Rotary kilns',2);
insert into sk_ibase_auxilary_data values ('20088','156','Motion Controls, Werkzeugmaschinen -> Rotary transfer machine',2);
insert into sk_ibase_auxilary_data values ('20089','139','Motion Control, Production machines -> Rubber',2);
insert into sk_ibase_auxilary_data values ('20090','128','Motion Controls, Kräne und Hebezeuge -> Rubber Tired Gantry Cranes (RTG)',2);
insert into sk_ibase_auxilary_data values ('20091','165','Allg. Antriebstechnologien -> Shears, cutters, saws, schredder',2);
insert into sk_ibase_auxilary_data values ('20092','111','Metall-/Metallurgie-Technologien -> Sheet-metal forming',2);
insert into sk_ibase_auxilary_data values ('20093','126','Motion Controls, Kräne und Hebezeuge -> Ship to Shore Cranes (STS)',2);
insert into sk_ibase_auxilary_data values ('20094','157','Motion Controls, Werkzeugmaschinen -> Slotter',2);
insert into sk_ibase_auxilary_data values ('20095','136','Motion Control, Production machines -> Solar Industry',2);
insert into sk_ibase_auxilary_data values ('20096','176','Allg. Antriebstechnologien -> Special applications',2);
insert into sk_ibase_auxilary_data values ('20097','158','Motion Controls, Werkzeugmaschinen -> Stamping',2);
insert into sk_ibase_auxilary_data values ('20098','198','Getriebe-Technologien -> Sugar mills',2);
insert into sk_ibase_auxilary_data values ('20099','133','Motion Control, Production machines -> Textile',2);
insert into sk_ibase_auxilary_data values ('20100','125','Papier- und Zellstoff-Technologien -> Tissue',2);
insert into sk_ibase_auxilary_data values ('20101','162','Motion Controls, Werkzeugmaschinen -> Transfer lines',2);
insert into sk_ibase_auxilary_data values ('20102','118','Bergbau-/Mining-Technologien -> Truck Application',2);
insert into sk_ibase_auxilary_data values ('20103','199','Getriebe-Technologien -> Tube mills',2);
insert into sk_ibase_auxilary_data values ('20104','160','Motion Controls, Werkzeugmaschinen -> Turning',2);
insert into sk_ibase_auxilary_data values ('20105','200','Getriebe-Technologien -> Vertical mills',2);
insert into sk_ibase_auxilary_data values ('20106','170','Allg. Antriebstechnologien -> Water Pump',2);
insert into sk_ibase_auxilary_data values ('20107','201','Getriebe-Technologien -> Water screw pumps',2);
insert into sk_ibase_auxilary_data values ('20108','119','Bergbau-/Mining-Technologien -> Water Solutions',2);
insert into sk_ibase_auxilary_data values ('20109','202','Getriebe-Technologien -> Water turbines',2);
insert into sk_ibase_auxilary_data values ('20110','203','Getriebe-Technologien -> Wet cooling towers',2);
insert into sk_ibase_auxilary_data values ('20111','137','Motion Control, Production machines -> Wind Energy',2);
insert into sk_ibase_auxilary_data values ('20112','206','Getriebe-Technologien -> Wind turbines (off-shore)',2);
insert into sk_ibase_auxilary_data values ('20113','205','Getriebe-Technologien -> Wind turbines (on-shore)',2);
insert into sk_ibase_auxilary_data values ('20114','141','Motion Control, Production machines -> Wire-Drawing',2);
insert into sk_ibase_auxilary_data values ('20115','134','Motion Control, Production machines -> Woodworking',2);


commit;