/***
*** Requester Name:  Sandeep
*** Purpose : SQL to add a coulmn for ELOP Quote Queue
*** Schema  : Core/Staging
*** Date of Request : 05/07/2017
***/

Insert into SK_SERVICE_PROPS (SERVICE_ID,SERVICE_NAME,SERVICE_ENDPOINT_NAME,MEDIA_TYPE_NAME,HTTP_METHOD_NAME,ISSSL,USER_NAME,PASS_WORD,SERVICE_METHOD,WSDL_PATH,NAMESPACE_URI,LOCALPART,MAX_CONNECTION,MAX_PER_ROUTE,DEFAULT_MAX_PER_ROUTE,CONNECTION_TIME_OUT,SOCKET_TIME_OUT,CON_REQUEST_TIMEOUT,ENABLE,SERVICE_CLASS_NAME,SERVICE_PORT_CLASS,REQUEST_CLASS_NAME,SERVICE_OPERATION,SERVICE_PORT_NAME,KEYSTORE,KEYSTORE_PWD,KEYSTORE_TYPE,TRUSTSTORE,TRUSTSTORE_PWD,TRUSTSTORE_TYPE,JMS_CONFIG_PATH,SERVICE_URI) values (99,'KAIROS.ELOP.QUOTE.COMMERCE.QUEUE','t3://vmohssiem072.oracleoutsourcing.com:42312',null,null,null,'wls_osb1','wls_osb1','JMS',null,null,null,4,null,1,48000,null,null,0,null,null,null,null,null,null,null,null,null,null,null,'JmsConnectionFactory','weblogic.jndi.WLInitialContextFactory');
commit;