/***
*** Requester Name:  Nimisha Dabral
*** Purpose : SK-54268
*** Schema  : Core
*** Date of Request : 21/08/2017
***/

INSERT into SK_SERVICE_PROPS (SERVICE_ID,SERVICE_NAME,SERVICE_ENDPOINT_NAME,MEDIA_TYPE_NAME,HTTP_METHOD_NAME,ISSSL,USER_NAME,PASS_WORD,SERVICE_METHOD,WSDL_PATH,NAMESPACE_URI,LOCALPART,MAX_CONNECTION,MAX_PER_ROUTE,DEFAULT_MAX_PER_ROUTE,CONNECTION_TIME_OUT,SOCKET_TIME_OUT,CON_REQUEST_TIMEOUT,ENABLE,SERVICE_CLASS_NAME,SERVICE_PORT_CLASS,REQUEST_CLASS_NAME,SERVICE_OPERATION,SERVICE_PORT_NAME,KEYSTORE,KEYSTORE_PWD,KEYSTORE_TYPE,TRUSTSTORE,TRUSTSTORE_PWD,TRUSTSTORE_TYPE,JMS_CONFIG_PATH,SERVICE_URI) values (30,'getDocumentList','https://osb-ebintegration2.siemens.com','application/json;charset=UTF-8','GET',0,null,null,'REST',null,null,null,100,20,20,100,100,100,1,null,null,null,null,null,null,null,null,null,null,null,null,'/osb/spice/v1/getDocumentList');
commit;